//========================================================================================
//  
//  $File: $
//  
//  Owner: Badr Nasser
//  
//  $Author: $
//  
//  $DateTime: $
//  
//  $Revision: $
//  
//  $Change: $
//  
//  Copyright 1997-2007 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================
REGISTER_PMINTERFACE(XLGActionComponent, kXLGActionComponentImpl)
REGISTER_PMINTERFACE(XLGDialogController, kXLGDialogControllerImpl)
REGISTER_PMINTERFACE(XLGDialogObserver, kXLGDialogObserverImpl)
REGISTER_PMINTERFACE(XLGFacade, kXLGFacadeImpl)
REGISTER_PMINTERFACE(XLGStartupShutdown, kXLGStartupShutdownImpl)
REGISTER_PMINTERFACE(XLGOpenDialogCmd, kXLGOpenDialogCmdImpl)
REGISTER_PMINTERFACE(XLGResponder, kXLGResponderImpl)
REGISTER_PMINTERFACE(XLGServiceProvider, kXLGServiceProviderImpl)
REGISTER_PMINTERFACE(XLGPreferences, kXLGPreferencesImpl)
REGISTER_PMINTERFACE(XLGXLGChechOutCmd, kXLGCheckOutCmdImpl)
REGISTER_PMINTERFACE(XLGChangeStatusDialogController, kXLGChangeStatusDialogControllerImpl)
REGISTER_PMINTERFACE(XLGChangeStatusDialogObserver, kXLGChangeStatusDialogObserverImpl)
REGISTER_PMINTERFACE(XLGAutoClosingDialog, kXLGAutoClosingDialogImpl)
REGISTER_PMINTERFACE(XLGTextModelObserver, kXLGTextModelObserverImpl)
REGISTER_PMINTERFACE(XLGDocObserver, kXLGDocObserverImpl)
REGISTER_PMINTERFACE(XLGAutoInitVariable, kXLGAutoInitVariableImpl)

//  Code generated by DollyXs code generator
